Completed the assigned task and fixed one bug
Farama-Foundation/Minari pull request #103
Opened 2023-06-30 15:19 UTC by Aaisha-Rani

* Added gymnasium Env id, File size on disk, and dataset group column to the Minari list local cli commands 

* Added dataset_group attribute, with  string Unknown as a placeholder value.

* Updated the Docs Data set standard and individual dataset pages.

* Fixed a bug  in point_maze_dataset.py

2023-07-02 07:04 UTC, balisujohn requested changes
When I run `minari list remote`I get a KeyError  for `dataset_group.` Since this is not implemented yet for our existing datasets, it should just default to Unknown if there is no `dataset_group`key present in metadata.

 `file_size` is not included in metadata, so it needs to be obtained a different way. I'm not 100% sure how, but this might be helpful https://stackoverflow.com/questions/50875461/google-cloud-storage-get-object-size-api.`file_size` also needs to be manually obtained for local datasets from the local hdf5 files, since there isn't an existing field where it's explicitly kept track of. 
 
To get the environment name, you should be able to access  `json.loads(dst_metadata["env_spec"])["id"]`

2023-07-02 07:07 UTC, balisujohn commented on minari/utils.py
> +
Looks like newlines added by accident.

2023-07-02 07:10 UTC, balisujohn commented on docs/tutorials/dataset_creation/point_maze_dataset.py
> +            dataset_id=dataset_name,
good catch

2024-01-25 16:11 UTC, younik commented
Closing for inactivity; thanks a lot for doing this anyway!

2024-01-25 16:11 UTC, closed without merging