Adding dtype test to main
Farama-Foundation/Minari pull request #113
Opened 2023-07-17 19:04 UTC by ronniepiku

# Description

A dummy env was created. And then test we're added to identify the supported dtypes.

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

### Screenshots

# Checklist:

- [x ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have run `pytest -v` and no errors are present.
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-07-17 22:55 UTC, rodrigodelazcano requested changes

2023-07-17 22:55 UTC, rodrigodelazcano commented on tests/test_supported_dtypes.py
> +import gym
```python
import gymnasium as gym
```

2023-07-19 13:26 UTC, balisujohn requested changes
Thanks for your work on this so far. I requested some changes and asked a clarifying question. I also think it would be good to add a table to the `dataset_standards.md` page it the doc clarifying which dtypes are supported for each space. Also, I noticed tests are failing, definitely please check that 

````
python3 -m pytest
````
and
````
pre-commit run --all-files
````
run without any issues locally.

2023-07-19 13:26 UTC, balisujohn commented on tests/test_supported_dtypes.py
> +test_box_dtypes()
these calls are unnecessary for tests

2023-07-19 13:26 UTC, balisujohn commented on minari/serialization.py
>      result = {}
what is the rationale behind these changes to serialization.py?

2023-08-02 16:05 UTC, ronniepiku commented on tests/common.py
> +            validate_component_dtype(
Looking back now, it seems that check_data_integrity is usesless so I have deleted it and used validate_component_dtype instead for the test. I also think this should take arguments of action_space, observation_space and expected_dtype. @balisujohn

2024-03-15 15:08 UTC, closed without merging