added dataset_size attribute to minari datasets
Farama-Foundation/Minari pull request #158
Opened 2023-10-29 13:17 UTC by shreyansjainn

# Description

added dataset size attribute to minari dataset generation function and cli. create a complimentary CLI PR #143 as refactoring of code introduced lot of conflicts. 

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

### Screenshots

> Please attach before and after screenshots of the change if applicable.
> To upload images to a PR -- simply drag and drop or copy paste.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have run `pytest -v` and no errors are present.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-10-29 13:27 UTC, shreyansjainn commented
hey @balisujohn @younik i've created this complimentary PR for #143 as there were a lot of conflicts due to code refactoring so i thought of doing the changes on the new structure from scratch. let me know if any more changes are required or not.

also, regarding the last change that John requested of getting the dataset size on the fly for a local dataset if the size is not present, i've not implemented that yet as i had to introduce a flag for `_show_dataset_table` method and it felt a bit cluttered. let me know if you'd like me to go ahead with that change or not. 

do let me know if any more changes are required in this.

2023-10-29 20:50 UTC, younik reviewed
Thanks for this PR; the code looks good, but I have a high-level doubt on how we want this to works.

The two possibilities are:
 - adding the size to the metadata, and just read it from it
 - Always "compute" it. It is not a real computation as the size is already stored in file metadata, but you have to iterate through files. 
 
For now you are doing the first option (however, in the get_dataset_size you are also computing for the cloud, that it would never use it as you call `get_dataset_size` only at the dataset creation).

I am personally more incline to the second simply because it is more robust to dataset changes however, it may slow down `minari list local` and `minari list remote`?
Can you maybe time the get_dataset_size method for datasets  with different number of file? (You can set a low max_episode_buffer on DataCollectorV0 to create datasets with many files)

2023-10-29 20:52 UTC, younik commented on minari/dataset/minari_storage.py
> +def get_dataset_size(dataset_id: str):
(Depending on the high-level choice on the main comment, I will tell you were to place it)

2023-10-31 17:01 UTC, shreyansjainn commented on minari/dataset/minari_storage.py
> +def get_dataset_size(dataset_id: str):
i can remove the gcp bucket part as anyway its not getting used, we are mainly calculating the size locally while creating the dataset only, so if i remove the gcp bucket part, even then should i move the method??

2023-10-31 17:02 UTC, shreyansjainn commented on minari/dataset/minari_dataset.py
> +        self._size = get_dataset_size(self._dataset_id)
sure, i'll remove it. i missed out on removing this.

2023-10-31 19:14 UTC, shreyansjainn commented
@younik, have implemented some corrections. one thing left to correct is the way the dataset size is getting written in metadata for `create_dataset_from_collector_env`, so give me some time to correct that, will correct the unit tests accordingly too

2023-11-02 21:56 UTC, younik commented
> @younik, have implemented some corrections. one thing left to correct is the way the dataset size is getting written in metadata for `create_dataset_from_collector_env`, so give me some time to correct that, will correct the unit tests accordingly too

Sounds good, let me know when you are already for another review

2023-11-04 16:08 UTC, shreyansjainn commented
@younik have implemented the changes in both the create dataset methods and changed the unit tests accordingly so that it tests that action too. do let me know if any other change is needed.

2023-11-09 00:25 UTC, younik requested changes

2023-11-09 00:25 UTC, younik commented on minari/dataset/minari_storage.py
> +def get_dataset_size(dataset_id: str):
Okay, last thing before merging I think
Can you make this a class function of MInariStorage, rename it to `get_size` and remove the dataset_id arg?
So you can get the size using `storage.get_size()`

You can get the data_path from the MinariStorage attribute.

2023-11-21 07:27 UTC, younik commented
Hey @shreyansjainn, what's the status of this? Do you need any help from my side?

2023-11-21 09:16 UTC, shreyansjainn commented
@younik will work on this today or by tomorrow, was on break due to diwali festival in india and post that the work rush kept me occupied, will finish this asap...

2023-11-21 21:20 UTC, younik reviewed
Looks good to me, just if you can do a small cleanup on the test code as suggested

2023-11-21 21:20 UTC, younik commented on tests/dataset/test_minari_storage.py
> +    assert dataset._data.metadata['dataset_size'] == dataset.storage.get_size()
use `storage` instead of `_data`

2023-11-21 21:20 UTC, younik commented on tests/dataset/test_minari_storage.py
> +    check_data_integrity(dataset._data, dataset.episode_indices)
same

2023-11-21 21:20 UTC, younik commented on tests/dataset/test_minari_storage.py
> +    # original_dataset_size = np.round(original_dataset_size / 1000000, 1)
remove unused code

2023-11-21 21:20 UTC, younik commented on tests/dataset/test_minari_storage.py
> +    assert dataset._data.metadata['dataset_size'] == dataset.storage.get_size()
use storage instead of _data

2023-11-21 21:20 UTC, younik commented on tests/dataset/test_minari_storage.py
> +    check_data_integrity(dataset._data, dataset.episode_indices)
same

2023-11-22 04:31 UTC, younik approved these changes
LGTM, thanks!

2023-11-22 04:32 UTC, merged