Added force_download flag for downloading locally existing datasets
Farama-Foundation/Minari pull request #90
Opened 2023-06-13 14:55 UTC by shreyansjainn

# Description

Currently, if the dataset exists locally, the download_dataset method just raises a warning and downloads the dataset anyway as mentioned in #79 . This change introduces a flag `force_download` which by default will be `False` and will not download the dataset if a local copy exists. Users can specify the `force_download` flag as `True` to override the setting and download a fresh copy of the dataset. 

For integration with CLI, the flag is fixed at `True` as the CLI already has a similar check present. For unit tests, the flag is fixed at `True` for testing the `download_dataset` method.

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have run `pytest -v` and no errors are present.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-06-13 17:03 UTC, younik commented on minari/storage/hosting.py
> +            sys.exit()
Why `sys.exit()` instead of an `if-else`?

2023-06-13 18:33 UTC, RedTachyon commented on minari/wrappers/error.py
> +class Error(Exception):
Do we need this? I know it exists in gymnasium which is already an interesting design choice (inherited from gym), but in that case it's probably better to just import it from there. Or just subclass `Exception` directly.

2023-06-13 18:51 UTC, shreyansjainn commented on minari/storage/hosting.py
> +        if not force_download:
i kept the initial version as the one just raising the warning, but after recommendation from @balisujohn i changed it to raising an exception so it becomes more explicit. If the exception is not needed I can revert the changes back to just the warning also. 

https://github.com/Farama-Foundation/Minari/pull/90#discussion_r1228446166

2023-06-13 19:07 UTC, balisujohn commented on minari/storage/hosting.py
> +        if not force_download:
I'll defer to @RedTachyon's opinion here, lets switch to a warning.

2023-06-14 19:01 UTC, balisujohn requested changes
Thanks for your work on this. I requested changes to the `download_dataset` function. Also please add a test asserting that the warning is correctly issued.

2023-06-14 20:21 UTC, RedTachyon commented on minari/storage/hosting.py
> +        if not force_download:
Yes, that's precisely what I was thinking, sorry if that wasn't clear. If the dataset is downloaded, just end the function, inform the user what happened and carry on.

2023-06-14 21:58 UTC, balisujohn approved these changes

2023-06-14 21:58 UTC, balisujohn commented
LGTM :^)

2023-06-14 22:03 UTC, merged