HuggingFace Integration
Farama-Foundation/Minari pull request #94
Opened 2023-06-20 09:32 UTC by balisujohn

# Description

Draft PR for hugging face Minari integration. Details to be announced.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have run `pytest -v` and no errors are present.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-06-26 10:26 UTC, younik requested changes
I added few comments on the functions, but overall I have some concerns on the API.

For the user, the current workflow is something like that:

```python
import gymnasium as gym
import minari
from minor import DataCollectorV0
from minari.integrations.hugging_face import (
    convert_hugging_face_dataset_to_minari_dataset,
    convert_minari_dataset_to_hugging_face_dataset,
    pull_dataset_from_hugging_face,
    push_dataset_to_hugging_face,
)

env = DataCollectorV0(gym.make("EnvName"))
... # code that generates the dataset
dataset = minari.create_dataset_from_collector_env(...)

hf_dataset = convert_minari_dataset_to_hugging_face_dataset(dataset)
push_dataset_to_hugging_face(hf_dataset, "name/repo")
```
and then
```python
hf_dataset = pull_dataset_from_hugging_face("name/repo")
dataset = convert_hugging_face_dataset_to_minari_dataset(hf_dataset)
```

The main red flag for me here is that we have public functions that are specifically for huggingface. I think this should be (more) transparent to the user, i.e. the function in `minari/integrations/hugging_face.py` are all private.

I have a couple of alternatives in mind:

### Add a HF flag to load and upload
```python
dataset = minari.load_dataset("name/repo", hugging_face_hub=True)
```
Which pull the dataset and return a `MinariDataset` that reads from HF dataset using the HuggingFaceStorage.

Similarly for pushing:
```python
minari.upload_dataset('dataset-name', hugging_face_hub=True)
```
Cons of this: 
 - we still have flags specifically for HF.
  - Load dataset directly from cloud, while we have a function `download_dataset`. I imagine, in the future, we also want the possibility to stream directly from the cloud: shall we drop `download_dataset`, and implicitly download on `load_dataset`?
  
  ### Use a setup_remote()
We discussed about having the possibility to setup different remotes than our GCP bucket. This is a particular case of that. We can create the API for that and use it in this case:

```python
minari.setup_remote(
      "https://huggingface.co/balisujohn",
      # others args like auth_key
)
```

And now every `load_dataset`/`upload_dataset` takes from/push to the HF hub directly as before, and conversions are done under the hood.
Cons:
 - Still, `download_dataset` it is no-sense
 - `setup_remote` should work also for GCP bucket and who knows
 - It complicates the library code as `setup_remote` changes other function behavior
 
 
 I am more prone for the second version, but it also requires more work

2023-07-01 22:33 UTC, RedTachyon reviewed
Note: I didn't do a comprehensive review of the code, just left a few comments for whatever stood out to me.

As for the higher-level design, I don't really mind having public functions in a separate `minari.integrations.hugging_face` namespace, if those are the ones that developers would use for pulling/uploading/converting. 
I'd potentially consider making the conversion back and forth automatic inside of the push/pull functions, depending on whether or not it makes any sense to operate on "raw" HF datasets in the context of Minari.

@younik can you elaborate on your issue with those functions being public? Imo the namespace makes it explicit enough, but I might be missing something.


As for the two alternative proposals:
- I'm not necessarily a fan of integrating it into the core `load_dataset` etc functions, we'd essentially tie core functionality to an external library and external servers. Keeping integrations separate (but accessible) is the right move imo
- `setup_remote` sounds like a somewhat more ambitious plan for the future, like being generic between GCP/AWS/Azure/HF/whatever else, so my guess is that it's not a solution for right now?

2023-07-01 22:33 UTC, RedTachyon commented on minari/integrations/hugging_face.py
> +        assert False, f"error, invalid observation or action structure{data}"
Is there a reason to `asset False` instead of just raising an exception?

2023-07-01 22:33 UTC, RedTachyon commented on minari/integrations/hugging_face.py
> +        author_email="wdudley@farama.org",
Probably settable from function arguments?

2023-07-04 17:05 UTC, younik commented
@RedTachyon 
One thing that it is likely to happen is that we support the HF data format, and then the conversion functions are no-op. We have `MinariStorage` that is designed to abstract to the dataset the difference on file formats (see https://github.com/Farama-Foundation/Minari/pull/94#discussion_r1241855457)

Also, if we want to support other libraries as well (e.g. [RLDS](https://github.com/google-research/rlds)), we need other conversion functions; I don't think this is interesting for the user.

And we may want to add some loading keywords to `load_dataset` and then they must be added also to `convert_hugging_face_dataset_to_minari_dataset` with the same semantics.

2023-08-28 15:44 UTC, elliottower commented on pyproject.toml
> +    "datasets>=2.13.0",
Should this be an optional requirement? Like install minari[huggingface]

2024-11-07 17:59 UTC, closed without merging